/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for hmFormatTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmFormatTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "hmFormatTable_interface.h"

const oid hmFormatTable_oid[] = { HMFORMATTABLE_OID };
const int hmFormatTable_oid_size = OID_LENGTH(hmFormatTable_oid);

    hmFormatTable_registration  hmFormatTable_user_context;

void initialize_table_hmFormatTable(void);
void shutdown_table_hmFormatTable(void);


/**
 * Initializes the hmFormatTable module
 */
void
init_hmFormatTable(void)
{
    DEBUGMSGTL(("verbose:hmFormatTable:init_hmFormatTable","called\n"));

    /*
     * TODO:300:o: Perform hmFormatTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("hmFormatTable"))
        initialize_table_hmFormatTable();

} /* init_hmFormatTable */

/**
 * Shut-down the hmFormatTable module (agent is exiting)
 */
void
shutdown_hmFormatTable(void)
{
    if (should_init("hmFormatTable"))
        shutdown_table_hmFormatTable();

}

/**
 * Initialize the table hmFormatTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_hmFormatTable(void)
{
    hmFormatTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:hmFormatTable:initialize_table_hmFormatTable","called\n"));

    /*
     * TODO:301:o: Perform hmFormatTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize hmFormatTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("hmFormatTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _hmFormatTable_initialize_interface(user_context, flags);
} /* initialize_table_hmFormatTable */

/**
 * Shutdown the table hmFormatTable 
 */
void
shutdown_table_hmFormatTable(void)
{
    /*
     * call interface shutdown code
     */
    _hmFormatTable_shutdown_interface(&hmFormatTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
hmFormatTable_rowreq_ctx_init(hmFormatTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:hmFormatTable:hmFormatTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra hmFormatTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* hmFormatTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void hmFormatTable_rowreq_ctx_cleanup(hmFormatTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:hmFormatTable:hmFormatTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra hmFormatTable rowreq cleanup.
     */
} /* hmFormatTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
hmFormatTable_pre_request(hmFormatTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:hmFormatTable:hmFormatTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform hmFormatTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* hmFormatTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
hmFormatTable_post_request(hmFormatTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:hmFormatTable:hmFormatTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform hmFormatTable post-request actions.
     */

    return MFD_SUCCESS;
} /* hmFormatTable_post_request */


/** @{ */
