/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef HMALBUMTABLE_DATA_ACCESS_H
#define HMALBUMTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmAlbumTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmAlbumTable is subid 1 of hmAlbum.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.4.1, length: 8
*/


    int hmAlbumTable_init_data(hmAlbumTable_registration * hmAlbumTable_reg);


    /*
     * TODO:180:o: Review hmAlbumTable cache timeout.
     * The number of seconds before the cache times out
     */
#define HMALBUMTABLE_CACHE_TIMEOUT   60

void hmAlbumTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void hmAlbumTable_container_shutdown(netsnmp_container *container_ptr);

int hmAlbumTable_container_load(netsnmp_container *container);
void hmAlbumTable_container_free(netsnmp_container *container);

int hmAlbumTable_cache_load(netsnmp_container *container);
void hmAlbumTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int hmAlbumTable_row_prep( hmAlbumTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* HMALBUMTABLE_DATA_ACCESS_H */
