/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef HMALBUMTABLE_INTERFACE_H
#define HMALBUMTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "hmAlbumTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _hmAlbumTable_initialize_interface(hmAlbumTable_registration * user_ctx,
                                    u_long flags);
void _hmAlbumTable_shutdown_interface(hmAlbumTable_registration * user_ctx);

hmAlbumTable_registration *
hmAlbumTable_registration_get( void );

hmAlbumTable_registration *
hmAlbumTable_registration_set( hmAlbumTable_registration * newreg );

netsnmp_container *hmAlbumTable_container_get( void );
int hmAlbumTable_container_size( void );

    hmAlbumTable_rowreq_ctx * hmAlbumTable_allocate_rowreq_ctx(void *);
void hmAlbumTable_release_rowreq_ctx(hmAlbumTable_rowreq_ctx *rowreq_ctx);

int hmAlbumTable_index_to_oid(netsnmp_index *oid_idx,
                            hmAlbumTable_mib_index *mib_idx);
int hmAlbumTable_index_from_oid(netsnmp_index *oid_idx,
                              hmAlbumTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void hmAlbumTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* HMALBUMTABLE_INTERFACE_H */
/** @} */
