/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef HMALBUMTABLE_OIDS_H
#define HMALBUMTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table hmAlbumTable */
#define HMALBUMTABLE_OID              1,3,6,1,3,2020,4,1


#define COLUMN_HMALBUMINDEX         1
    
#define COLUMN_HMALBUMDESCR         2
    

#define HMALBUMTABLE_MIN_COL   COLUMN_HMALBUMINDEX
#define HMALBUMTABLE_MAX_COL   COLUMN_HMALBUMDESCR
    


#ifdef __cplusplus
}
#endif

#endif /* HMALBUMTABLE_OIDS_H */
