/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file hmAlbumTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef HMALBUMTABLE_DATA_GET_H
#define HMALBUMTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmAlbumTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmAlbumTable is subid 1 of hmAlbum.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.4.1, length: 8
*/
    /*
     * indexes
     */

    int hmAlbumDescr_get( hmAlbumTable_rowreq_ctx *rowreq_ctx, char **hmAlbumDescr_val_ptr_ptr, size_t *hmAlbumDescr_val_ptr_len_ptr );


int hmAlbumTable_indexes_set_tbl_idx(hmAlbumTable_mib_index *tbl_idx, long hmAlbumIndex_val);
int hmAlbumTable_indexes_set(hmAlbumTable_rowreq_ctx *rowreq_ctx, long hmAlbumIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* HMALBUMTABLE_DATA_GET_H */
/** @} */
