/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmAllMusicTable.h"


#include "hmAllMusicTable_data_access.h"

/** @ingroup interface
 * @addtogroup data_access data_access: Routines to access data
 *
 * These routines are used to locate the data used to satisfy
 * requests.
 * 
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmAllMusicTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmAllMusicTable is subid 1 of hmAllMusic.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.1.1, length: 8
*/

/**
 * initialization for hmAllMusicTable data access
 *
 * This function is called during startup to allow you to
 * allocate any resources you need for the data table.
 *
 * @param hmAllMusicTable_reg
 *        Pointer to hmAllMusicTable_registration
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : unrecoverable error.
 */
int
hmAllMusicTable_init_data(hmAllMusicTable_registration * hmAllMusicTable_reg)
{
    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_init_data","called\n"));

    /*
     * TODO:303:o: Initialize hmAllMusicTable data.
     */
    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
    static unsigned int my_columns[] = {
            COLUMN_HMALLMUSICINDEX,
            COLUMN_HMALLMUSICSTYLE,
            COLUMN_HMALLMUSICARTIST,
            COLUMN_HMALLMUSICALBUM,
            COLUMN_HMALLMUSICNAME,
            COLUMN_HMALLMUSICDURATION,
            COLUMN_HMALLMUSICSIZE,
            COLUMN_HMALLMUSICFORMAT
    };
    static netsnmp_column_info valid_columns;
    valid_columns.isRange = 0;
    valid_columns.details.list = my_columns;
    valid_columns.list_count = sizeof(my_columns)/sizeof(unsigned int);
    hmAllMusicTable_valid_columns_set(&valid_columns);
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/

    return MFD_SUCCESS;
} /* hmAllMusicTable_init_data */

/**
 * container overview
 *
 */

/**
 * container initialization
 *
 * @param container_ptr_ptr A pointer to a container pointer. If you
 *        create a custom container, use this parameter to return it
 *        to the MFD helper. If set to NULL, the MFD helper will
 *        allocate a container for you.
 * @param  cache A pointer to a cache structure. You can set the timeout
 *         and other cache flags using this pointer.
 *
 *  This function is called at startup to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases. If no custom
 *  container is allocated, the MFD code will create one for your.
 *
 *  This is also the place to set up cache behavior. The default, to
 *  simply set the cache timeout, will work well with the default
 *  container. If you are using a custom container, you may want to
 *  look at the cache helper documentation to see if there are any
 *  flags you want to set.
 *
 * @remark
 *  This would also be a good place to do any initialization needed
 *  for you data source. For example, opening a connection to another
 *  process that will supply the data, opening a database, etc.
 */
void
hmAllMusicTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache)
{
    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_container_init","called\n"));
    
    if (NULL == container_ptr_ptr) {
        snmp_log(LOG_ERR,"bad container param to hmAllMusicTable_container_init\n");
        return;
    }

    /*
     * For advanced users, you can use a custom container. If you
     * do not create one, one will be created for you.
     */
    *container_ptr_ptr = NULL;

    if (NULL == cache) {
        snmp_log(LOG_ERR,"bad cache param to hmAllMusicTable_container_init\n");
        return;
    }

    /*
     * TODO:345:A: Set up hmAllMusicTable cache properties.
     *
     * Also for advanced users, you can set parameters for the
     * cache. Do not change the magic pointer, as it is used
     * by the MFD helper. To completely disable caching, set
     * cache->enabled to 0.
     */
    cache->timeout = HMALLMUSICTABLE_CACHE_TIMEOUT; /* seconds */
} /* hmAllMusicTable_container_init */

/**
 * container shutdown
 *
 * @param container_ptr A pointer to the container.
 *
 *  This function is called at shutdown to allow you to customize certain
 *  aspects of the access method. For the most part, it is for advanced
 *  users. The default code should suffice for most cases.
 *
 *  This function is called before hmAllMusicTable_container_free().
 *
 * @remark
 *  This would also be a good place to do any cleanup needed
 *  for you data source. For example, closing a connection to another
 *  process that supplied the data, closing a database, etc.
 */
void
hmAllMusicTable_container_shutdown(netsnmp_container *container_ptr)
{
    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_container_shutdown","called\n"));
    
    if (NULL == container_ptr) {
        snmp_log(LOG_ERR,"bad params to hmAllMusicTable_container_shutdown\n");
        return;
    }

} /* hmAllMusicTable_container_shutdown */

/**
 * load initial data
 *
 * TODO:350:M: Implement hmAllMusicTable data load
 * This function will also be called by the cache helper to load
 * the container again (after the container free function has been
 * called to free the previous contents).
 *
 * @param container container to which items should be inserted
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_RESOURCE_UNAVAILABLE : Can't access data source
 * @retval MFD_ERROR                : other error.
 *
 *  This function is called to load the index(es) (and data, optionally)
 *  for the every row in the data set.
 *
 * @remark
 *  While loading the data, the only important thing is the indexes.
 *  If access to your data is cheap/fast (e.g. you have a pointer to a
 *  structure in memory), it would make sense to update the data here.
 *  If, however, the accessing the data invovles more work (e.g. parsing
 *  some other existing data, or peforming calculations to derive the data),
 *  then you can limit yourself to setting the indexes and saving any
 *  information you will need later. Then use the saved information in
 *  hmAllMusicTable_row_prep() for populating data.
 *
 * @note
 *  If you need consistency between rows (like you want statistics
 *  for each row to be from the same time frame), you should set all
 *  data here.
 *
 */
int
hmAllMusicTable_container_load(netsnmp_container *container)
{
    hmAllMusicTable_rowreq_ctx *rowreq_ctx;
    size_t                 count = 0;

    
    //index
    int     hmAllMusicIndex;
    //style
    int     hmAllMusicStyle;
    //artist
    int     hmAllMusicArtist;
    //album
    int     hmAllMusicAlbum;
    //name
    char    hmAllMusicName[80];
    size_t  hmAllMusicName_len;
    //duration
    int     hmAllMusicDuration;
    //size
    int     hmAllMusicSize;
    //file format
    int     hmAllMusicFormat;

    
    FILE *filep;
    char line[MAX_LINE_SIZE];

    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_container_load","called\n"));

  
    filep = fopen("/etc/hostmusicmib.conf/allmusicTable.conf", "r");
    if(NULL ==  filep) {
        return MFD_RESOURCE_UNAVAILABLE;
    }

    
    while( 1 ) {
   
        do {
            if (!fgets(line, sizeof(line), filep)) {
                /* we're done */
                fclose(filep);
                filep = NULL;
            }
        } while (filep && (line[0] == '\n'));

  
        if(NULL == filep)    break;

        line[strlen(line)-1]='\0';
        char* token; 
        char* rest = line;

        token = strtok_r(rest, ";", &rest);
        hmAllMusicIndex = atoi(token);

        token = strtok_r(rest, ";", &rest);
        hmAllMusicStyle = atoi(token);

        token = strtok_r(rest, ";", &rest);
        hmAllMusicArtist = atoi(token);

        token = strtok_r(rest, ";", &rest);
        hmAllMusicAlbum = atoi(token);

        token = strtok_r(rest, ";", &rest);
        strcpy(hmAllMusicName,token);
        hmAllMusicName_len = strlen(hmAllMusicName);

        token = strtok_r(rest, ";", &rest);
        hmAllMusicDuration = atoi(token);

        token = strtok_r(rest, ";", &rest);
        hmAllMusicSize = atoi(token);

        token = strtok_r(rest, ";", &rest);
        hmAllMusicFormat = atoi(token);


        rowreq_ctx = hmAllMusicTable_allocate_rowreq_ctx(NULL);
        if (NULL == rowreq_ctx) {
            snmp_log(LOG_ERR, "memory allocation failed\n");
            return MFD_RESOURCE_UNAVAILABLE;
        }
        if(MFD_SUCCESS != hmAllMusicTable_indexes_set(rowreq_ctx
                               , hmAllMusicIndex
               )) {
            snmp_log(LOG_ERR,"error setting index while loading "
                     "hmAllMusicTable data.\n");
            hmAllMusicTable_release_rowreq_ctx(rowreq_ctx);
            continue;
        }

        /** no mapping */
        rowreq_ctx->data.hmAllMusicStyle = hmAllMusicStyle;
    
    
        /** no mapping */
        rowreq_ctx->data.hmAllMusicArtist = hmAllMusicArtist;
        
   
        /** no mapping */
        rowreq_ctx->data.hmAllMusicAlbum = hmAllMusicAlbum;
        
  
        /** no mapping */
        rowreq_ctx->data.hmAllMusicName_len = 255;

        if ((NULL == rowreq_ctx->data.hmAllMusicName) ||
            (rowreq_ctx->data.hmAllMusicName_len <
            (hmAllMusicName_len* sizeof(hmAllMusicName[0])))) {
            snmp_log(LOG_ERR,"not enough space for value (hmAllMusicName)\n");
            return MFD_ERROR;
        }
        rowreq_ctx->data.hmAllMusicName_len = hmAllMusicName_len* sizeof(hmAllMusicName[0]);
        memcpy( rowreq_ctx->data.hmAllMusicName, hmAllMusicName, hmAllMusicName_len* sizeof(hmAllMusicName[0]) );
        
    
        /** no mapping */
        rowreq_ctx->data.hmAllMusicDuration = hmAllMusicDuration;
        
    
        /** no mapping */
        rowreq_ctx->data.hmAllMusicSize = hmAllMusicSize;
        
    
        /** no mapping */
        rowreq_ctx->data.hmAllMusicFormat = hmAllMusicFormat;
        
        
        CONTAINER_INSERT(container, rowreq_ctx);
        ++count;
    }

   
    if(NULL != filep)
        fclose(filep);
    
    DEBUGMSGT(("verbose:hmAllMusicTable:hmAllMusicTable_container_load",
               "inserted %ld records\n", count));

    return MFD_SUCCESS;
} /* hmAllMusicTable_container_load */

/**
 * container clean up
 *
 * @param container container with all current items
 *
 *  This optional callback is called prior to all
 *  item's being removed from the container. If you
 *  need to do any processing before that, do it here.
 *
 * @note
 *  The MFD helper will take care of releasing all the row contexts.
 *
 */
void
hmAllMusicTable_container_free(netsnmp_container *container)
{
    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_container_free","called\n"));

    /*
     * TODO:380:M: Free hmAllMusicTable container data.
     */
} /* hmAllMusicTable_container_free */

/**
 * prepare row for processing.
 *
 *  When the agent has located the row for a request, this function is
 *  called to prepare the row for processing. If you fully populated
 *  the data context during the index setup phase, you may not need to
 *  do anything.
 *
 * @param rowreq_ctx pointer to a context.
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 */
int
hmAllMusicTable_row_prep( hmAllMusicTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_row_prep","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

    /*
     * TODO:390:o: Prepare row for request.
     * If populating row data was delayed, this is the place to
     * fill in the row for this request.
     */

    return MFD_SUCCESS;
} /* hmAllMusicTable_row_prep */

/** @} */
