/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmAllMusicTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement hmAllMusicTable get routines.
 * TODO:240:M: Implement hmAllMusicTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmAllMusicTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmAllMusicTable is subid 1 of hmAllMusic.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.1.1, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement hmAllMusicTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param hmAllMusicIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
hmAllMusicTable_indexes_set_tbl_idx(hmAllMusicTable_mib_index *tbl_idx, long hmAllMusicIndex_val)
{
    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_indexes_set_tbl_idx","called\n"));

    /* hmAllMusicIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->hmAllMusicIndex = hmAllMusicIndex_val;
    

    return MFD_SUCCESS;
} /* hmAllMusicTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
hmAllMusicTable_indexes_set(hmAllMusicTable_rowreq_ctx *rowreq_ctx, long hmAllMusicIndex_val)
{
    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicTable_indexes_set","called\n"));

    if(MFD_SUCCESS != hmAllMusicTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , hmAllMusicIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != hmAllMusicTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* hmAllMusicTable_indexes_set */


/*---------------------------------------------------------------------
 * HOST-MUSIC-MIB::hmAllMusicEntry.hmAllMusicStyle
 * hmAllMusicStyle is subid 2 of hmAllMusicEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.2020.1.1.1.2
 * Description:
Numero correspondente ao estilo de musica na hmStyleTable.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the hmAllMusicStyle data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param hmAllMusicStyle_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
hmAllMusicStyle_get( hmAllMusicTable_rowreq_ctx *rowreq_ctx, long * hmAllMusicStyle_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != hmAllMusicStyle_val_ptr );


    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicStyle_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the hmAllMusicStyle data.
 * copy (* hmAllMusicStyle_val_ptr ) from rowreq_ctx->data
 */
    (* hmAllMusicStyle_val_ptr ) = rowreq_ctx->data.hmAllMusicStyle;

    return MFD_SUCCESS;
} /* hmAllMusicStyle_get */

/*---------------------------------------------------------------------
 * HOST-MUSIC-MIB::hmAllMusicEntry.hmAllMusicArtist
 * hmAllMusicArtist is subid 3 of hmAllMusicEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.2020.1.1.1.3
 * Description:
Numero correspondente ao artista da musica na hmArtistTable.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the hmAllMusicArtist data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param hmAllMusicArtist_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
hmAllMusicArtist_get( hmAllMusicTable_rowreq_ctx *rowreq_ctx, long * hmAllMusicArtist_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != hmAllMusicArtist_val_ptr );


    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicArtist_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the hmAllMusicArtist data.
 * copy (* hmAllMusicArtist_val_ptr ) from rowreq_ctx->data
 */
    (* hmAllMusicArtist_val_ptr ) = rowreq_ctx->data.hmAllMusicArtist;

    return MFD_SUCCESS;
} /* hmAllMusicArtist_get */

/*---------------------------------------------------------------------
 * HOST-MUSIC-MIB::hmAllMusicEntry.hmAllMusicAlbum
 * hmAllMusicAlbum is subid 4 of hmAllMusicEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.2020.1.1.1.4
 * Description:
Numero correspondente ao album da musica na hmAlbumTable.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 0      hashint   0
 *   settable   0
 *
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the hmAllMusicAlbum data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param hmAllMusicAlbum_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
hmAllMusicAlbum_get( hmAllMusicTable_rowreq_ctx *rowreq_ctx, long * hmAllMusicAlbum_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != hmAllMusicAlbum_val_ptr );


    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicAlbum_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the hmAllMusicAlbum data.
 * copy (* hmAllMusicAlbum_val_ptr ) from rowreq_ctx->data
 */
    (* hmAllMusicAlbum_val_ptr ) = rowreq_ctx->data.hmAllMusicAlbum;

    return MFD_SUCCESS;
} /* hmAllMusicAlbum_get */

/*---------------------------------------------------------------------
 * HOST-MUSIC-MIB::hmAllMusicEntry.hmAllMusicName
 * hmAllMusicName is subid 5 of hmAllMusicEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.2020.1.1.1.5
 * Description:
Nome da musica.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   1
 *   settable   0
 *   hint: 255a
 *
 * Ranges:  0 - 255;
 *
 * Its syntax is DisplayString (based on perltype OCTETSTR)
 * The net-snmp type is ASN_OCTET_STR. The C type decl is char (char)
 * This data type requires a length.  (Max 255)
 */
/**
 * Extract the current value of the hmAllMusicName data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param hmAllMusicName_val_ptr_ptr
 *        Pointer to storage for a char variable
 * @param hmAllMusicName_val_ptr_len_ptr
 *        Pointer to a size_t. On entry, it will contain the size (in bytes)
 *        pointed to by hmAllMusicName.
 *        On exit, this value should contain the data size (in bytes).
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
*
 * @note If you need more than (*hmAllMusicName_val_ptr_len_ptr) bytes of memory,
 *       allocate it using malloc() and update hmAllMusicName_val_ptr_ptr.
 *       <b>DO NOT</b> free the previous pointer.
 *       The MFD helper will release the memory you allocate.
 *
 * @remark If you call this function yourself, you are responsible
 *         for checking if the pointer changed, and freeing any
 *         previously allocated memory. (Not necessary if you pass
 *         in a pointer to static memory, obviously.)
 */
int
hmAllMusicName_get( hmAllMusicTable_rowreq_ctx *rowreq_ctx, char **hmAllMusicName_val_ptr_ptr, size_t *hmAllMusicName_val_ptr_len_ptr )
{
   /** we should have a non-NULL pointer and enough storage */
   netsnmp_assert( (NULL != hmAllMusicName_val_ptr_ptr) && (NULL != *hmAllMusicName_val_ptr_ptr));
   netsnmp_assert( NULL != hmAllMusicName_val_ptr_len_ptr );


    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicName_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the hmAllMusicName data.
 * copy (* hmAllMusicName_val_ptr_ptr ) data and (* hmAllMusicName_val_ptr_len_ptr ) from rowreq_ctx->data
 */
    /*
     * make sure there is enough space for hmAllMusicName data
     */
    if ((NULL == (* hmAllMusicName_val_ptr_ptr )) ||
        ((* hmAllMusicName_val_ptr_len_ptr ) <
         (rowreq_ctx->data.hmAllMusicName_len* sizeof(rowreq_ctx->data.hmAllMusicName[0])))) {
        /*
         * allocate space for hmAllMusicName data
         */
        (* hmAllMusicName_val_ptr_ptr ) = malloc(rowreq_ctx->data.hmAllMusicName_len* sizeof(rowreq_ctx->data.hmAllMusicName[0]));
        if(NULL == (* hmAllMusicName_val_ptr_ptr )) {
            snmp_log(LOG_ERR,"could not allocate memory (rowreq_ctx->data.hmAllMusicName)\n");
            return MFD_ERROR;
        }
    }
    (* hmAllMusicName_val_ptr_len_ptr ) = rowreq_ctx->data.hmAllMusicName_len* sizeof(rowreq_ctx->data.hmAllMusicName[0]);
    memcpy( (* hmAllMusicName_val_ptr_ptr ), rowreq_ctx->data.hmAllMusicName, rowreq_ctx->data.hmAllMusicName_len* sizeof(rowreq_ctx->data.hmAllMusicName[0]) );

    return MFD_SUCCESS;
} /* hmAllMusicName_get */

/*---------------------------------------------------------------------
 * HOST-MUSIC-MIB::hmAllMusicEntry.hmAllMusicDuration
 * hmAllMusicDuration is subid 6 of hmAllMusicEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.2020.1.1.1.6
 * Description:
Duracao da musica.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the hmAllMusicDuration data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param hmAllMusicDuration_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
hmAllMusicDuration_get( hmAllMusicTable_rowreq_ctx *rowreq_ctx, long * hmAllMusicDuration_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != hmAllMusicDuration_val_ptr );


    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicDuration_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the hmAllMusicDuration data.
 * copy (* hmAllMusicDuration_val_ptr ) from rowreq_ctx->data
 */
    (* hmAllMusicDuration_val_ptr ) = rowreq_ctx->data.hmAllMusicDuration;

    return MFD_SUCCESS;
} /* hmAllMusicDuration_get */

/*---------------------------------------------------------------------
 * HOST-MUSIC-MIB::hmAllMusicEntry.hmAllMusicSize
 * hmAllMusicSize is subid 7 of hmAllMusicEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.2020.1.1.1.7
 * Description:
Tamanho digital da musica.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the hmAllMusicSize data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param hmAllMusicSize_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
hmAllMusicSize_get( hmAllMusicTable_rowreq_ctx *rowreq_ctx, long * hmAllMusicSize_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != hmAllMusicSize_val_ptr );


    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicSize_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the hmAllMusicSize data.
 * copy (* hmAllMusicSize_val_ptr ) from rowreq_ctx->data
 */
    (* hmAllMusicSize_val_ptr ) = rowreq_ctx->data.hmAllMusicSize;

    return MFD_SUCCESS;
} /* hmAllMusicSize_get */

/*---------------------------------------------------------------------
 * HOST-MUSIC-MIB::hmAllMusicEntry.hmAllMusicFormat
 * hmAllMusicFormat is subid 8 of hmAllMusicEntry.
 * Its status is Current, and its access level is ReadOnly.
 * OID: .1.3.6.1.3.2020.1.1.1.8
 * Description:
Numero correspondente ao formato da musica na hmFormatTable.
 *
 * Attributes:
 *   accessible 1     isscalar 0     enums  0      hasdefval 0
 *   readable   1     iscolumn 1     ranges 1      hashint   0
 *   settable   0
 *
 * Ranges:  0 - 2147483647;
 *
 * Its syntax is INTEGER32 (based on perltype INTEGER32)
 * The net-snmp type is ASN_INTEGER. The C type decl is long (long)
 */
/**
 * Extract the current value of the hmAllMusicFormat data.
 *
 * Set a value using the data context for the row.
 *
 * @param rowreq_ctx
 *        Pointer to the row request context.
 * @param hmAllMusicFormat_val_ptr
 *        Pointer to storage for a long variable
 *
 * @retval MFD_SUCCESS         : success
 * @retval MFD_SKIP            : skip this node (no value for now)
 * @retval MFD_ERROR           : Any other error
 */
int
hmAllMusicFormat_get( hmAllMusicTable_rowreq_ctx *rowreq_ctx, long * hmAllMusicFormat_val_ptr )
{
   /** we should have a non-NULL pointer */
   netsnmp_assert( NULL != hmAllMusicFormat_val_ptr );


    DEBUGMSGTL(("verbose:hmAllMusicTable:hmAllMusicFormat_get","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);

/*
 * TODO:231:o: |-> Extract the current value of the hmAllMusicFormat data.
 * copy (* hmAllMusicFormat_val_ptr ) from rowreq_ctx->data
 */
    (* hmAllMusicFormat_val_ptr ) = rowreq_ctx->data.hmAllMusicFormat;

    return MFD_SUCCESS;
} /* hmAllMusicFormat_get */



/** @} */
