/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for hmStyleTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmStyleTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "hmStyleTable_interface.h"

const oid hmStyleTable_oid[] = { HMSTYLETABLE_OID };
const int hmStyleTable_oid_size = OID_LENGTH(hmStyleTable_oid);

    hmStyleTable_registration  hmStyleTable_user_context;

void initialize_table_hmStyleTable(void);
void shutdown_table_hmStyleTable(void);


/**
 * Initializes the hmStyleTable module
 */
void
init_hmStyleTable(void)
{
    DEBUGMSGTL(("verbose:hmStyleTable:init_hmStyleTable","called\n"));

    /*
     * TODO:300:o: Perform hmStyleTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("hmStyleTable"))
        initialize_table_hmStyleTable();

} /* init_hmStyleTable */

/**
 * Shut-down the hmStyleTable module (agent is exiting)
 */
void
shutdown_hmStyleTable(void)
{
    if (should_init("hmStyleTable"))
        shutdown_table_hmStyleTable();

}

/**
 * Initialize the table hmStyleTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_hmStyleTable(void)
{
    hmStyleTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:hmStyleTable:initialize_table_hmStyleTable","called\n"));

    /*
     * TODO:301:o: Perform hmStyleTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize hmStyleTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("hmStyleTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _hmStyleTable_initialize_interface(user_context, flags);
} /* initialize_table_hmStyleTable */

/**
 * Shutdown the table hmStyleTable 
 */
void
shutdown_table_hmStyleTable(void)
{
    /*
     * call interface shutdown code
     */
    _hmStyleTable_shutdown_interface(&hmStyleTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
hmStyleTable_rowreq_ctx_init(hmStyleTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:hmStyleTable:hmStyleTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra hmStyleTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* hmStyleTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void hmStyleTable_rowreq_ctx_cleanup(hmStyleTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:hmStyleTable:hmStyleTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra hmStyleTable rowreq cleanup.
     */
} /* hmStyleTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
hmStyleTable_pre_request(hmStyleTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:hmStyleTable:hmStyleTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform hmStyleTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* hmStyleTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
hmStyleTable_post_request(hmStyleTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:hmStyleTable:hmStyleTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform hmStyleTable post-request actions.
     */

    return MFD_SUCCESS;
} /* hmStyleTable_post_request */


/** @{ */
