/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for hmAlbumTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmAlbumTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "hmAlbumTable_interface.h"

const oid hmAlbumTable_oid[] = { HMALBUMTABLE_OID };
const int hmAlbumTable_oid_size = OID_LENGTH(hmAlbumTable_oid);

    hmAlbumTable_registration  hmAlbumTable_user_context;

void initialize_table_hmAlbumTable(void);
void shutdown_table_hmAlbumTable(void);


/**
 * Initializes the hmAlbumTable module
 */
void
init_hmAlbumTable(void)
{
    DEBUGMSGTL(("verbose:hmAlbumTable:init_hmAlbumTable","called\n"));

    /*
     * TODO:300:o: Perform hmAlbumTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("hmAlbumTable"))
        initialize_table_hmAlbumTable();

} /* init_hmAlbumTable */

/**
 * Shut-down the hmAlbumTable module (agent is exiting)
 */
void
shutdown_hmAlbumTable(void)
{
    if (should_init("hmAlbumTable"))
        shutdown_table_hmAlbumTable();

}

/**
 * Initialize the table hmAlbumTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_hmAlbumTable(void)
{
    hmAlbumTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:hmAlbumTable:initialize_table_hmAlbumTable","called\n"));

    /*
     * TODO:301:o: Perform hmAlbumTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize hmAlbumTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("hmAlbumTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _hmAlbumTable_initialize_interface(user_context, flags);
} /* initialize_table_hmAlbumTable */

/**
 * Shutdown the table hmAlbumTable 
 */
void
shutdown_table_hmAlbumTable(void)
{
    /*
     * call interface shutdown code
     */
    _hmAlbumTable_shutdown_interface(&hmAlbumTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
hmAlbumTable_rowreq_ctx_init(hmAlbumTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:hmAlbumTable:hmAlbumTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra hmAlbumTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* hmAlbumTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void hmAlbumTable_rowreq_ctx_cleanup(hmAlbumTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:hmAlbumTable:hmAlbumTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra hmAlbumTable rowreq cleanup.
     */
} /* hmAlbumTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
hmAlbumTable_pre_request(hmAlbumTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:hmAlbumTable:hmAlbumTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform hmAlbumTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* hmAlbumTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
hmAlbumTable_post_request(hmAlbumTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:hmAlbumTable:hmAlbumTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform hmAlbumTable post-request actions.
     */

    return MFD_SUCCESS;
} /* hmAlbumTable_post_request */


/** @{ */
