/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmPlaylistTable.h"


/** @defgroup data_get data_get: Routines to get data
 *
 * TODO:230:M: Implement hmPlaylistTable get routines.
 * TODO:240:M: Implement hmPlaylistTable mapping routines (if any).
 *
 * These routine are used to get the value for individual objects. The
 * row context is passed, along with a pointer to the memory where the
 * value should be copied.
 *
 * @{
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmPlaylistTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmPlaylistTable is subid 1 of hmPlay.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.6.1, length: 8
*/

/* ---------------------------------------------------------------------
 * TODO:200:r: Implement hmPlaylistTable data context functions.
 */


/**
 * set mib index(es)
 *
 * @param tbl_idx mib index structure
 * @param hmPlaylistIndex_val
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This convenience function is useful for setting all the MIB index
 *  components with a single function call. It is assume that the C values
 *  have already been mapped from their native/rawformat to the MIB format.
 */
int
hmPlaylistTable_indexes_set_tbl_idx(hmPlaylistTable_mib_index *tbl_idx, long hmPlaylistIndex_val)
{
    DEBUGMSGTL(("verbose:hmPlaylistTable:hmPlaylistTable_indexes_set_tbl_idx","called\n"));

    /* hmPlaylistIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h */
    tbl_idx->hmPlaylistIndex = hmPlaylistIndex_val;
    

    return MFD_SUCCESS;
} /* hmPlaylistTable_indexes_set_tbl_idx */

/**
 * @internal
 * set row context indexes
 *
 * @param reqreq_ctx the row context that needs updated indexes
 *
 * @retval MFD_SUCCESS     : success.
 * @retval MFD_ERROR       : other error.
 *
 * @remark
 *  This function sets the mib indexs, then updates the oid indexs
 *  from the mib index.
 */
int
hmPlaylistTable_indexes_set(hmPlaylistTable_rowreq_ctx *rowreq_ctx, long hmPlaylistIndex_val)
{
    DEBUGMSGTL(("verbose:hmPlaylistTable:hmPlaylistTable_indexes_set","called\n"));

    if(MFD_SUCCESS != hmPlaylistTable_indexes_set_tbl_idx(&rowreq_ctx->tbl_idx
                                   , hmPlaylistIndex_val
           ))
        return MFD_ERROR;

    /*
     * convert mib index to oid index
     */
    rowreq_ctx->oid_idx.len = sizeof(rowreq_ctx->oid_tmp) / sizeof(oid);
    if(0 != hmPlaylistTable_index_to_oid(&rowreq_ctx->oid_idx,
                                    &rowreq_ctx->tbl_idx)) {
        return MFD_ERROR;
    }

    return MFD_SUCCESS;
} /* hmPlaylistTable_indexes_set */




/** @} */
