/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for hmPlaylistTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmPlaylistTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "hmPlaylistTable_interface.h"

const oid hmPlaylistTable_oid[] = { HMPLAYLISTTABLE_OID };
const int hmPlaylistTable_oid_size = OID_LENGTH(hmPlaylistTable_oid);

    hmPlaylistTable_registration  hmPlaylistTable_user_context;

void initialize_table_hmPlaylistTable(void);
void shutdown_table_hmPlaylistTable(void);


/**
 * Initializes the hmPlaylistTable module
 */
void
init_hmPlaylistTable(void)
{
    DEBUGMSGTL(("verbose:hmPlaylistTable:init_hmPlaylistTable","called\n"));

    /*
     * TODO:300:o: Perform hmPlaylistTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("hmPlaylistTable"))
        initialize_table_hmPlaylistTable();

} /* init_hmPlaylistTable */

/**
 * Shut-down the hmPlaylistTable module (agent is exiting)
 */
void
shutdown_hmPlaylistTable(void)
{
    if (should_init("hmPlaylistTable"))
        shutdown_table_hmPlaylistTable();

}

/**
 * Initialize the table hmPlaylistTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_hmPlaylistTable(void)
{
    hmPlaylistTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:hmPlaylistTable:initialize_table_hmPlaylistTable","called\n"));

    /*
     * TODO:301:o: Perform hmPlaylistTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize hmPlaylistTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("hmPlaylistTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _hmPlaylistTable_initialize_interface(user_context, flags);
} /* initialize_table_hmPlaylistTable */

/**
 * Shutdown the table hmPlaylistTable 
 */
void
shutdown_table_hmPlaylistTable(void)
{
    /*
     * call interface shutdown code
     */
    _hmPlaylistTable_shutdown_interface(&hmPlaylistTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
hmPlaylistTable_rowreq_ctx_init(hmPlaylistTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:hmPlaylistTable:hmPlaylistTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra hmPlaylistTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* hmPlaylistTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void hmPlaylistTable_rowreq_ctx_cleanup(hmPlaylistTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:hmPlaylistTable:hmPlaylistTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra hmPlaylistTable rowreq cleanup.
     */
} /* hmPlaylistTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
hmPlaylistTable_pre_request(hmPlaylistTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:hmPlaylistTable:hmPlaylistTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform hmPlaylistTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* hmPlaylistTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
hmPlaylistTable_post_request(hmPlaylistTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:hmPlaylistTable:hmPlaylistTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform hmPlaylistTable post-request actions.
     */

    return MFD_SUCCESS;
} /* hmPlaylistTable_post_request */


/** @{ */
