/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
/** \page MFD helper for hmArtistTable
 *
 * \section intro Introduction
 * Introductory text.
 *
 */
/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-features.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "hmArtistTable.h"

#include <net-snmp/agent/mib_modules.h>

#include "hmArtistTable_interface.h"

const oid hmArtistTable_oid[] = { HMARTISTTABLE_OID };
const int hmArtistTable_oid_size = OID_LENGTH(hmArtistTable_oid);

    hmArtistTable_registration  hmArtistTable_user_context;

void initialize_table_hmArtistTable(void);
void shutdown_table_hmArtistTable(void);


/**
 * Initializes the hmArtistTable module
 */
void
init_hmArtistTable(void)
{
    DEBUGMSGTL(("verbose:hmArtistTable:init_hmArtistTable","called\n"));

    /*
     * TODO:300:o: Perform hmArtistTable one-time module initialization.
     */
     
    /*
     * here we initialize all the tables we're planning on supporting
     */
    if (should_init("hmArtistTable"))
        initialize_table_hmArtistTable();

} /* init_hmArtistTable */

/**
 * Shut-down the hmArtistTable module (agent is exiting)
 */
void
shutdown_hmArtistTable(void)
{
    if (should_init("hmArtistTable"))
        shutdown_table_hmArtistTable();

}

/**
 * Initialize the table hmArtistTable 
 *    (Define its contents and how it's structured)
 */
void
initialize_table_hmArtistTable(void)
{
    hmArtistTable_registration * user_context;
    u_long flags;

    DEBUGMSGTL(("verbose:hmArtistTable:initialize_table_hmArtistTable","called\n"));

    /*
     * TODO:301:o: Perform hmArtistTable one-time table initialization.
     */

    /*
     * TODO:302:o: |->Initialize hmArtistTable user context
     * if you'd like to pass in a pointer to some data for this
     * table, allocate or set it up here.
     */
    /*
     * a netsnmp_data_list is a simple way to store void pointers. A simple
     * string token is used to add, find or remove pointers.
     */
    user_context = netsnmp_create_data_list("hmArtistTable", NULL, NULL);
    
    /*
     * No support for any flags yet, but in the future you would
     * set any flags here.
     */
    flags = 0;
    
    /*
     * call interface initialization code
     */
    _hmArtistTable_initialize_interface(user_context, flags);
} /* initialize_table_hmArtistTable */

/**
 * Shutdown the table hmArtistTable 
 */
void
shutdown_table_hmArtistTable(void)
{
    /*
     * call interface shutdown code
     */
    _hmArtistTable_shutdown_interface(&hmArtistTable_user_context);
}

/**
 * extra context initialization (eg default values)
 *
 * @param rowreq_ctx    : row request context
 * @param user_init_ctx : void pointer for user (parameter to rowreq_ctx_allocate)
 *
 * @retval MFD_SUCCESS  : no errors
 * @retval MFD_ERROR    : error (context allocate will fail)
 */
int
hmArtistTable_rowreq_ctx_init(hmArtistTable_rowreq_ctx *rowreq_ctx,
                           void *user_init_ctx)
{
    DEBUGMSGTL(("verbose:hmArtistTable:hmArtistTable_rowreq_ctx_init","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:210:o: |-> Perform extra hmArtistTable rowreq initialization. (eg DEFVALS)
     */

    return MFD_SUCCESS;
} /* hmArtistTable_rowreq_ctx_init */

/**
 * extra context cleanup
 *
 */
void hmArtistTable_rowreq_ctx_cleanup(hmArtistTable_rowreq_ctx *rowreq_ctx)
{
    DEBUGMSGTL(("verbose:hmArtistTable:hmArtistTable_rowreq_ctx_cleanup","called\n"));

    netsnmp_assert(NULL != rowreq_ctx);
    
    /*
     * TODO:211:o: |-> Perform extra hmArtistTable rowreq cleanup.
     */
} /* hmArtistTable_rowreq_ctx_cleanup */

/**
 * pre-request callback
 *
 *
 * @retval MFD_SUCCESS              : success.
 * @retval MFD_ERROR                : other error
 */
int
hmArtistTable_pre_request(hmArtistTable_registration * user_context)
{
    DEBUGMSGTL(("verbose:hmArtistTable:hmArtistTable_pre_request","called\n"));

    /*
     * TODO:510:o: Perform hmArtistTable pre-request actions.
     */

    return MFD_SUCCESS;
} /* hmArtistTable_pre_request */

/**
 * post-request callback
 *
 * Note:
 *   New rows have been inserted into the container, and
 *   deleted rows have been removed from the container and
 *   released.
 *
 * @param user_context
 * @param rc : MFD_SUCCESS if all requests succeeded
 *
 * @retval MFD_SUCCESS : success.
 * @retval MFD_ERROR   : other error (ignored)
 */
int
hmArtistTable_post_request(hmArtistTable_registration * user_context, int rc)
{
    DEBUGMSGTL(("verbose:hmArtistTable:hmArtistTable_post_request","called\n"));

    /*
     * TODO:511:o: Perform hmArtistTable post-request actions.
     */

    return MFD_SUCCESS;
} /* hmArtistTable_post_request */


/** @{ */
