/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef HMSTYLETABLE_OIDS_H
#define HMSTYLETABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table hmStyleTable */
#define HMSTYLETABLE_OID              1,3,6,1,3,2020,2,1


#define COLUMN_HMSTYLEINDEX         1
    
#define COLUMN_HMSTYLEDESCR         2
    

#define HMSTYLETABLE_MIN_COL   COLUMN_HMSTYLEINDEX
#define HMSTYLETABLE_MAX_COL   COLUMN_HMSTYLEDESCR
    


#ifdef __cplusplus
}
#endif

#endif /* HMSTYLETABLE_OIDS_H */
