/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
#ifndef HMSTYLETABLE_H
#define HMSTYLETABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(HOST-MUSIC-MIB)
config_require(HOST-MUSIC-MIB/hmStyleTable/hmStyleTable_interface)
config_require(HOST-MUSIC-MIB/hmStyleTable/hmStyleTable_data_access)
config_require(HOST-MUSIC-MIB/hmStyleTable/hmStyleTable_data_get)
config_require(HOST-MUSIC-MIB/hmStyleTable/hmStyleTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for hmStyleTable */
#include "hmStyleTable_oids.h"

/* enum definions */
#include "hmStyleTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_hmStyleTable(void);
void shutdown_hmStyleTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmStyleTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmStyleTable is subid 1 of hmStyle.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.2.1, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review hmStyleTable registration context.
     */
typedef netsnmp_data_list hmStyleTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review hmStyleTable data context structure.
 * This structure is used to represent the data for hmStyleTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * hmStyleTable.
 */
typedef struct hmStyleTable_data_s {
    
        /*
         * hmStyleDescr(2)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   hmStyleDescr[255];
size_t      hmStyleDescr_len; /* # of char elements, not bytes */
    
} hmStyleTable_data;


/*
 * TODO:120:r: |-> Review hmStyleTable mib index.
 * This structure is used to represent the index for hmStyleTable.
 */
typedef struct hmStyleTable_mib_index_s {

        /*
         * hmStyleIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   hmStyleIndex;


} hmStyleTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review hmStyleTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_hmStyleTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review hmStyleTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * hmStyleTable_rowreq_ctx pointer.
 */
typedef struct hmStyleTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_hmStyleTable_IDX_LEN];
    
    hmStyleTable_mib_index        tbl_idx;
    
    hmStyleTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to hmStyleTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *hmStyleTable_data_list;

} hmStyleTable_rowreq_ctx;

typedef struct hmStyleTable_ref_rowreq_ctx_s {
    hmStyleTable_rowreq_ctx *rowreq_ctx;
} hmStyleTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int hmStyleTable_pre_request(hmStyleTable_registration * user_context);
    int hmStyleTable_post_request(hmStyleTable_registration * user_context,
        int rc);

    int hmStyleTable_rowreq_ctx_init(hmStyleTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void hmStyleTable_rowreq_ctx_cleanup(hmStyleTable_rowreq_ctx *rowreq_ctx);


    hmStyleTable_rowreq_ctx *
                  hmStyleTable_row_find_by_mib_index(hmStyleTable_mib_index *mib_idx);

extern const oid hmStyleTable_oid[];
extern const int hmStyleTable_oid_size;


#include "hmStyleTable_interface.h"
#include "hmStyleTable_data_access.h"
#include "hmStyleTable_data_get.h"
#include "hmStyleTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* HMSTYLETABLE_H */
/** @} */
