/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef HMSTYLETABLE_INTERFACE_H
#define HMSTYLETABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "hmStyleTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _hmStyleTable_initialize_interface(hmStyleTable_registration * user_ctx,
                                    u_long flags);
void _hmStyleTable_shutdown_interface(hmStyleTable_registration * user_ctx);

hmStyleTable_registration *
hmStyleTable_registration_get( void );

hmStyleTable_registration *
hmStyleTable_registration_set( hmStyleTable_registration * newreg );

netsnmp_container *hmStyleTable_container_get( void );
int hmStyleTable_container_size( void );

    hmStyleTable_rowreq_ctx * hmStyleTable_allocate_rowreq_ctx(void *);
void hmStyleTable_release_rowreq_ctx(hmStyleTable_rowreq_ctx *rowreq_ctx);

int hmStyleTable_index_to_oid(netsnmp_index *oid_idx,
                            hmStyleTable_mib_index *mib_idx);
int hmStyleTable_index_from_oid(netsnmp_index *oid_idx,
                              hmStyleTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void hmStyleTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* HMSTYLETABLE_INTERFACE_H */
/** @} */
