/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef HMFORMATTABLE_INTERFACE_H
#define HMFORMATTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "hmFormatTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _hmFormatTable_initialize_interface(hmFormatTable_registration * user_ctx,
                                    u_long flags);
void _hmFormatTable_shutdown_interface(hmFormatTable_registration * user_ctx);

hmFormatTable_registration *
hmFormatTable_registration_get( void );

hmFormatTable_registration *
hmFormatTable_registration_set( hmFormatTable_registration * newreg );

netsnmp_container *hmFormatTable_container_get( void );
int hmFormatTable_container_size( void );

    hmFormatTable_rowreq_ctx * hmFormatTable_allocate_rowreq_ctx(void *);
void hmFormatTable_release_rowreq_ctx(hmFormatTable_rowreq_ctx *rowreq_ctx);

int hmFormatTable_index_to_oid(netsnmp_index *oid_idx,
                            hmFormatTable_mib_index *mib_idx);
int hmFormatTable_index_from_oid(netsnmp_index *oid_idx,
                              hmFormatTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void hmFormatTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* HMFORMATTABLE_INTERFACE_H */
/** @} */
