/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef HMFORMATTABLE_OIDS_H
#define HMFORMATTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table hmFormatTable */
#define HMFORMATTABLE_OID              1,3,6,1,3,2020,5,1


#define COLUMN_HMFORMATINDEX         1
    
#define COLUMN_HMFORMATDESCR         2
    

#define HMFORMATTABLE_MIN_COL   COLUMN_HMFORMATINDEX
#define HMFORMATTABLE_MAX_COL   COLUMN_HMFORMATDESCR
    


#ifdef __cplusplus
}
#endif

#endif /* HMFORMATTABLE_OIDS_H */
