/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file hmFormatTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef HMFORMATTABLE_DATA_GET_H
#define HMFORMATTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmFormatTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmFormatTable is subid 1 of hmFormat.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.5.1, length: 8
*/
    /*
     * indexes
     */

    int hmFormatDescr_get( hmFormatTable_rowreq_ctx *rowreq_ctx, char **hmFormatDescr_val_ptr_ptr, size_t *hmFormatDescr_val_ptr_len_ptr );


int hmFormatTable_indexes_set_tbl_idx(hmFormatTable_mib_index *tbl_idx, long hmFormatIndex_val);
int hmFormatTable_indexes_set(hmFormatTable_rowreq_ctx *rowreq_ctx, long hmFormatIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* HMFORMATTABLE_DATA_GET_H */
/** @} */
