/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef HMFORMATTABLE_DATA_ACCESS_H
#define HMFORMATTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmFormatTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmFormatTable is subid 1 of hmFormat.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.5.1, length: 8
*/


    int hmFormatTable_init_data(hmFormatTable_registration * hmFormatTable_reg);


    /*
     * TODO:180:o: Review hmFormatTable cache timeout.
     * The number of seconds before the cache times out
     */
#define HMFORMATTABLE_CACHE_TIMEOUT   60

void hmFormatTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void hmFormatTable_container_shutdown(netsnmp_container *container_ptr);

int hmFormatTable_container_load(netsnmp_container *container);
void hmFormatTable_container_free(netsnmp_container *container);

int hmFormatTable_cache_load(netsnmp_container *container);
void hmFormatTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int hmFormatTable_row_prep( hmFormatTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* HMFORMATTABLE_DATA_ACCESS_H */
