/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef HMPLAYLISTTABLE_INTERFACE_H
#define HMPLAYLISTTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "hmPlaylistTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _hmPlaylistTable_initialize_interface(hmPlaylistTable_registration * user_ctx,
                                    u_long flags);
void _hmPlaylistTable_shutdown_interface(hmPlaylistTable_registration * user_ctx);

hmPlaylistTable_registration *
hmPlaylistTable_registration_get( void );

hmPlaylistTable_registration *
hmPlaylistTable_registration_set( hmPlaylistTable_registration * newreg );

netsnmp_container *hmPlaylistTable_container_get( void );
int hmPlaylistTable_container_size( void );

    hmPlaylistTable_rowreq_ctx * hmPlaylistTable_allocate_rowreq_ctx(void *);
void hmPlaylistTable_release_rowreq_ctx(hmPlaylistTable_rowreq_ctx *rowreq_ctx);

int hmPlaylistTable_index_to_oid(netsnmp_index *oid_idx,
                            hmPlaylistTable_mib_index *mib_idx);
int hmPlaylistTable_index_from_oid(netsnmp_index *oid_idx,
                              hmPlaylistTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void hmPlaylistTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* HMPLAYLISTTABLE_INTERFACE_H */
/** @} */
