/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef HMPLAYLISTTABLE_OIDS_H
#define HMPLAYLISTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table hmPlaylistTable */
#define HMPLAYLISTTABLE_OID              1,3,6,1,3,2020,6,1


#define COLUMN_HMPLAYLISTINDEX         1
    

#define HMPLAYLISTTABLE_MIN_COL   COLUMN_HMPLAYLISTINDEX
#define HMPLAYLISTTABLE_MAX_COL   COLUMN_HMPLAYLISTINDEX
    


#ifdef __cplusplus
}
#endif

#endif /* HMPLAYLISTTABLE_OIDS_H */
