/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file hmPlaylistTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef HMPLAYLISTTABLE_DATA_GET_H
#define HMPLAYLISTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmPlaylistTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmPlaylistTable is subid 1 of hmPlay.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.6.1, length: 8
*/
    /*
     * indexes
     */



int hmPlaylistTable_indexes_set_tbl_idx(hmPlaylistTable_mib_index *tbl_idx, long hmPlaylistIndex_val);
int hmPlaylistTable_indexes_set(hmPlaylistTable_rowreq_ctx *rowreq_ctx, long hmPlaylistIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* HMPLAYLISTTABLE_DATA_GET_H */
/** @} */
