/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-get.m2c
 *
 * @file hmArtistTable_data_get.h
 *
 * @addtogroup get
 *
 * Prototypes for get functions
 *
 * @{
 */
#ifndef HMARTISTTABLE_DATA_GET_H
#define HMARTISTTABLE_DATA_GET_H

#ifdef __cplusplus
extern "C" {
#endif

/* *********************************************************************
 * GET function declarations
 */

/* *********************************************************************
 * GET Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmArtistTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmArtistTable is subid 1 of hmArtist.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.3.1, length: 8
*/
    /*
     * indexes
     */

    int hmArtistDescr_get( hmArtistTable_rowreq_ctx *rowreq_ctx, char **hmArtistDescr_val_ptr_ptr, size_t *hmArtistDescr_val_ptr_len_ptr );


int hmArtistTable_indexes_set_tbl_idx(hmArtistTable_mib_index *tbl_idx, long hmArtistIndex_val);
int hmArtistTable_indexes_set(hmArtistTable_rowreq_ctx *rowreq_ctx, long hmArtistIndex_val);




#ifdef __cplusplus
}
#endif

#endif /* HMARTISTTABLE_DATA_GET_H */
/** @} */
