/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef HMARTISTTABLE_DATA_ACCESS_H
#define HMARTISTTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmArtistTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmArtistTable is subid 1 of hmArtist.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.3.1, length: 8
*/


    int hmArtistTable_init_data(hmArtistTable_registration * hmArtistTable_reg);


    /*
     * TODO:180:o: Review hmArtistTable cache timeout.
     * The number of seconds before the cache times out
     */
#define HMARTISTTABLE_CACHE_TIMEOUT   60

void hmArtistTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void hmArtistTable_container_shutdown(netsnmp_container *container_ptr);

int hmArtistTable_container_load(netsnmp_container *container);
void hmArtistTable_container_free(netsnmp_container *container);

int hmArtistTable_cache_load(netsnmp_container *container);
void hmArtistTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int hmArtistTable_row_prep( hmArtistTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* HMARTISTTABLE_DATA_ACCESS_H */
