/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef HMARTISTTABLE_OIDS_H
#define HMARTISTTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table hmArtistTable */
#define HMARTISTTABLE_OID              1,3,6,1,3,2020,3,1


#define COLUMN_HMARTISTINDEX         1
    
#define COLUMN_HMARTISTDESCR         2
    

#define HMARTISTTABLE_MIN_COL   COLUMN_HMARTISTINDEX
#define HMARTISTTABLE_MAX_COL   COLUMN_HMARTISTDESCR
    


#ifdef __cplusplus
}
#endif

#endif /* HMARTISTTABLE_OIDS_H */
