/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-top.m2c
 */
#ifndef HMALLMUSICTABLE_H
#define HMALLMUSICTABLE_H

#ifdef __cplusplus
extern "C" {
#endif


/** @addtogroup misc misc: Miscellaneous routines
 *
 * @{
 */
#include <net-snmp/library/asn1.h>

/* other required module components */
    /* *INDENT-OFF*  */
config_add_mib(HOST-MUSIC-MIB)
config_require(HOST-MUSIC-MIB/hmAllMusicTable/hmAllMusicTable_interface)
config_require(HOST-MUSIC-MIB/hmAllMusicTable/hmAllMusicTable_data_access)
config_require(HOST-MUSIC-MIB/hmAllMusicTable/hmAllMusicTable_data_get)
config_require(HOST-MUSIC-MIB/hmAllMusicTable/hmAllMusicTable_data_set)
    /* *INDENT-ON*  */

/* OID and column number definitions for hmAllMusicTable */
#include "hmAllMusicTable_oids.h"

/* enum definions */
#include "hmAllMusicTable_enums.h"

/* *********************************************************************
 * function declarations
 */
void init_hmAllMusicTable(void);
void shutdown_hmAllMusicTable(void);

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmAllMusicTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmAllMusicTable is subid 1 of hmAllMusic.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.1.1, length: 8
*/
/* *********************************************************************
 * When you register your mib, you get to provide a generic
 * pointer that will be passed back to you for most of the
 * functions calls.
 *
 * TODO:100:r: Review all context structures
 */
    /*
     * TODO:101:o: |-> Review hmAllMusicTable registration context.
     */
typedef netsnmp_data_list hmAllMusicTable_registration;

/**********************************************************************/
/*
 * TODO:110:r: |-> Review hmAllMusicTable data context structure.
 * This structure is used to represent the data for hmAllMusicTable.
 */
/*
 * This structure contains storage for all the columns defined in the
 * hmAllMusicTable.
 */
typedef struct hmAllMusicTable_data_s {
    
        /*
         * hmAllMusicStyle(2)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   hmAllMusicStyle;
    
        /*
         * hmAllMusicArtist(3)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   hmAllMusicArtist;
    
        /*
         * hmAllMusicAlbum(4)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/r/d/h
         */
   long   hmAllMusicAlbum;
    
        /*
         * hmAllMusicName(5)/DisplayString/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H
         */
   char   hmAllMusicName[255];
size_t      hmAllMusicName_len; /* # of char elements, not bytes */
    
        /*
         * hmAllMusicDuration(6)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   hmAllMusicDuration;
    
        /*
         * hmAllMusicSize(7)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   hmAllMusicSize;
    
        /*
         * hmAllMusicFormat(8)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   hmAllMusicFormat;
    
} hmAllMusicTable_data;


/*
 * TODO:120:r: |-> Review hmAllMusicTable mib index.
 * This structure is used to represent the index for hmAllMusicTable.
 */
typedef struct hmAllMusicTable_mib_index_s {

        /*
         * hmAllMusicIndex(1)/INTEGER32/ASN_INTEGER/long(long)//l/A/w/e/R/d/h
         */
   long   hmAllMusicIndex;


} hmAllMusicTable_mib_index;

    /*
     * TODO:121:r: |   |-> Review hmAllMusicTable max index length.
     * If you KNOW that your indexes will never exceed a certain
     * length, update this macro to that length.
*/
#define MAX_hmAllMusicTable_IDX_LEN     1


/* *********************************************************************
 * TODO:130:o: |-> Review hmAllMusicTable Row request (rowreq) context.
 * When your functions are called, you will be passed a
 * hmAllMusicTable_rowreq_ctx pointer.
 */
typedef struct hmAllMusicTable_rowreq_ctx_s {

    /** this must be first for container compare to work */
    netsnmp_index        oid_idx;
    oid                  oid_tmp[MAX_hmAllMusicTable_IDX_LEN];
    
    hmAllMusicTable_mib_index        tbl_idx;
    
    hmAllMusicTable_data              data;

    /*
     * flags per row. Currently, the first (lower) 8 bits are reserved
     * for the user. See mfd.h for other flags.
     */
    u_int                       rowreq_flags;

    /*
     * TODO:131:o: |   |-> Add useful data to hmAllMusicTable rowreq context.
     */
    
    /*
     * storage for future expansion
     */
    netsnmp_data_list             *hmAllMusicTable_data_list;

} hmAllMusicTable_rowreq_ctx;

typedef struct hmAllMusicTable_ref_rowreq_ctx_s {
    hmAllMusicTable_rowreq_ctx *rowreq_ctx;
} hmAllMusicTable_ref_rowreq_ctx;

/* *********************************************************************
 * function prototypes
 */
    int hmAllMusicTable_pre_request(hmAllMusicTable_registration * user_context);
    int hmAllMusicTable_post_request(hmAllMusicTable_registration * user_context,
        int rc);

    int hmAllMusicTable_rowreq_ctx_init(hmAllMusicTable_rowreq_ctx *rowreq_ctx,
                                   void *user_init_ctx);
    void hmAllMusicTable_rowreq_ctx_cleanup(hmAllMusicTable_rowreq_ctx *rowreq_ctx);


    hmAllMusicTable_rowreq_ctx *
                  hmAllMusicTable_row_find_by_mib_index(hmAllMusicTable_mib_index *mib_idx);

extern const oid hmAllMusicTable_oid[];
extern const int hmAllMusicTable_oid_size;


#include "hmAllMusicTable_interface.h"
#include "hmAllMusicTable_data_access.h"
#include "hmAllMusicTable_data_get.h"
#include "hmAllMusicTable_data_set.h"

/*
 * DUMMY markers, ignore
 *
 * TODO:099:x: *************************************************************
 * TODO:199:x: *************************************************************
 * TODO:299:x: *************************************************************
 * TODO:399:x: *************************************************************
 * TODO:499:x: *************************************************************
 */

#ifdef __cplusplus
}
#endif

#endif /* HMALLMUSICTABLE_H */
/** @} */
