/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-data-access.m2c
 */
#ifndef HMALLMUSICTABLE_DATA_ACCESS_H
#define HMALLMUSICTABLE_DATA_ACCESS_H

#ifdef __cplusplus
extern "C" {
#endif


/* *********************************************************************
 * function declarations
 */

/* *********************************************************************
 * Table declarations
 */
/**********************************************************************
 **********************************************************************
 ***
 *** Table hmAllMusicTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * HOST-MUSIC-MIB::hmAllMusicTable is subid 1 of hmAllMusic.
 * Its status is Current.
 * OID: .1.3.6.1.3.2020.1.1, length: 8
*/


    int hmAllMusicTable_init_data(hmAllMusicTable_registration * hmAllMusicTable_reg);


    /*
     * TODO:180:o: Review hmAllMusicTable cache timeout.
     * The number of seconds before the cache times out
     */
#define HMALLMUSICTABLE_CACHE_TIMEOUT   60

void hmAllMusicTable_container_init(netsnmp_container **container_ptr_ptr,
                             netsnmp_cache *cache);
void hmAllMusicTable_container_shutdown(netsnmp_container *container_ptr);

int hmAllMusicTable_container_load(netsnmp_container *container);
void hmAllMusicTable_container_free(netsnmp_container *container);

int hmAllMusicTable_cache_load(netsnmp_container *container);
void hmAllMusicTable_cache_free(netsnmp_container *container);

    /*
    ***************************************************
    ***             START EXAMPLE CODE              ***
    ***---------------------------------------------***/
/* *********************************************************************
 * Since we have no idea how you really access your data, we'll go with
 * a worst case example: a flat text file.
 */
#define MAX_LINE_SIZE 256
    /*
    ***---------------------------------------------***
    ***              END  EXAMPLE CODE              ***
    ***************************************************/
    int hmAllMusicTable_row_prep( hmAllMusicTable_rowreq_ctx *rowreq_ctx);



#ifdef __cplusplus
}
#endif

#endif /* HMALLMUSICTABLE_DATA_ACCESS_H */
