/*
 * Note: this file originally auto-generated by mib2c
 * using mfd-interface.m2c
 */
/** @ingroup interface: Routines to interface to Net-SNMP
 *
 * \warning This code should not be modified, called directly,
 *          or used to interpret functionality. It is subject to
 *          change at any time.
 * 
 * @{
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */
#ifndef HMALLMUSICTABLE_INTERFACE_H
#define HMALLMUSICTABLE_INTERFACE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "hmAllMusicTable.h"


/* ********************************************************************
 * Table declarations
 */

/* PUBLIC interface initialization routine */
void _hmAllMusicTable_initialize_interface(hmAllMusicTable_registration * user_ctx,
                                    u_long flags);
void _hmAllMusicTable_shutdown_interface(hmAllMusicTable_registration * user_ctx);

hmAllMusicTable_registration *
hmAllMusicTable_registration_get( void );

hmAllMusicTable_registration *
hmAllMusicTable_registration_set( hmAllMusicTable_registration * newreg );

netsnmp_container *hmAllMusicTable_container_get( void );
int hmAllMusicTable_container_size( void );

    hmAllMusicTable_rowreq_ctx * hmAllMusicTable_allocate_rowreq_ctx(void *);
void hmAllMusicTable_release_rowreq_ctx(hmAllMusicTable_rowreq_ctx *rowreq_ctx);

int hmAllMusicTable_index_to_oid(netsnmp_index *oid_idx,
                            hmAllMusicTable_mib_index *mib_idx);
int hmAllMusicTable_index_from_oid(netsnmp_index *oid_idx,
                              hmAllMusicTable_mib_index *mib_idx);

/*
 * access to certain internals. use with caution!
 */
void hmAllMusicTable_valid_columns_set(netsnmp_column_info *vc);


#ifdef __cplusplus
}
#endif

#endif /* HMALLMUSICTABLE_INTERFACE_H */
/** @} */
