/*
 * Note: this file originally auto-generated by mib2c
 * using generic-table-oids.m2c
 */
#ifndef HMALLMUSICTABLE_OIDS_H
#define HMALLMUSICTABLE_OIDS_H

#ifdef __cplusplus
extern "C" {
#endif


/* column number definitions for table hmAllMusicTable */
#define HMALLMUSICTABLE_OID              1,3,6,1,3,2020,1,1


#define COLUMN_HMALLMUSICINDEX         1
    
#define COLUMN_HMALLMUSICSTYLE         2
    
#define COLUMN_HMALLMUSICARTIST         3
    
#define COLUMN_HMALLMUSICALBUM         4
    
#define COLUMN_HMALLMUSICNAME         5
    
#define COLUMN_HMALLMUSICDURATION         6
    
#define COLUMN_HMALLMUSICSIZE         7
    
#define COLUMN_HMALLMUSICFORMAT         8
    

#define HMALLMUSICTABLE_MIN_COL   COLUMN_HMALLMUSICINDEX
#define HMALLMUSICTABLE_MAX_COL   COLUMN_HMALLMUSICFORMAT
    


#ifdef __cplusplus
}
#endif

#endif /* HMALLMUSICTABLE_OIDS_H */
