/*
 * Note: this file originally auto-generated by mib2c
 * using mib2c.scalar.conf
 */
#ifndef HOSTMUSICMIB_H
#define HOSTMUSICMIB_H

/* custom function declarations */
/*void escreverPlaylist();
void playSong();
void removerMusica();
void sigchld_handler(int sig);
void adicionarMusica(int m);
void limparPlaylist();
int readMusic();
/* function declarations */
void init_hostMusicMIB(void);
Netsnmp_Node_Handler handle_hmPlayMusic;
Netsnmp_Node_Handler handle_hmAddtoPlaylist;
Netsnmp_Node_Handler handle_hmPlayStatus;

#endif /* HOSTMUSICMIB_H */
